apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data
  namespace: argocd-matrix

spec:
  project: default

  source:
    repoURL: https://github.com/vanlit/matrix-synapse-on-aks.git
    targetRevision: main
    path: apps/30-data
    directory:
      recurse: false
      jsonnet: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-matrix

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
