apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network
  namespace: matrix-argocd

spec:
  project: default

  source:
    repoURL: https://github.com/vanlit/matrix-synapse-on-aks.git
    targetRevision: main
    path: apps/50-network

  directory:
    recurse: false
    jsonnet: {}
    exclude: "**/*.tpl"

  destination:
    server: https://kubernetes.default.svc
    namespace: matrix-argocd