apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix-db-auth
  namespace: 

spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault

  target:
    name: matrix-db-auth
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth

  data:
    - secretKey: username
      remoteRef:
        key: matrix-postgres-username

    - secretKey: password
      remoteRef:
        key: postgres-password