apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: matrix-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"

spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 22.0.7

    helm:
      values: |
        architecture: replication

        auth:
          enabled: true
          existingSecret: redis-auth

        master:
          persistence:
            enabled: true
            size: 8Gi

        replica:
          replicaCount: 1

          persistence:
            enabled: true
            size: 8Gi

        sentinel:
          enabled: true

        metrics:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: redis

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true